=== Evinett/medical-term-pipeline/src/main/resources/output_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Extracted Medical Terms",
  "type": "object",
  "properties": {
    "diagnoses": {
      "$ref": "#/definitions/structuredTermArray"
    },
    "procedures": {
      "$ref": "#/definitions/structuredTermArray"
    },
    "medications_and_treatments": {
      "$ref": "#/definitions/medicationTermArray"
    },
    "tests": {
      "$ref": "#/definitions/structuredTermArray"
    },
    "clinical_narrative": {
      "$ref": "#/definitions/narrativeTermArray"
    }
  },
  "required": [
    "diagnoses",
    "procedures",
    "medications_and_treatments",
    "tests",
    "clinical_narrative"
  ],
  "definitions": {
    "structuredTermObject": {
      "type": "object",
      "properties": {
        "term_text": {
          "type": "string",
          "minLength": 1
        },
        "omop_domain": {
          "type": "string",
          "minLength": 1
        },
        "OMOP_ID": {
          "type": "string"
        }
      },
      "required": [
        "term_text",
        "omop_domain"
      ],
      "additionalProperties": false
    },
    "medicationTermObject": {
      "type": "object",
      "properties": {
        "term_text": {
          "type": "string",
          "minLength": 1
        },
        "omop_domain": {
          "type": "string",
          "minLength": 1
        },
        "OMOP_ID": {
          "type": "string"
        },
        "details": {
          "type": "object"
        }
      },
      "required": [
        "term_text",
        "omop_domain"
      ],
      "additionalProperties": false
    },
    "narrativeTermObject": {
      "type": "object",
      "properties": {
        "term_text": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "term_text"
      ],
      "additionalProperties": false
    },
    "structuredTermArray": {
      "type": "array",
      "items": { "$ref": "#/definitions/structuredTermObject" }
    },
    "medicationTermArray": {
      "type": "array",
      "items": { "$ref": "#/definitions/medicationTermObject" }
    },
    "narrativeTermArray": {
      "type": "array",
      "items": { "$ref": "#/definitions/narrativeTermObject" }
    }
  }
}

=== Evinett/medical-term-pipeline/output/note_32_D2N032_terms.json
{
  "diagnoses" : [ {
    "term_text" : "PCOS",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Cholecystectomy",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Right hip degenerative joint disease",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "Cortisone injection into her right hip joint",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "NSAID PRN by mouth",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "MR arthrogram of the right hip",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_56_D2N056_terms.json
{
  "diagnoses" : [ {
    "term_text" : "Recurrent lung infections",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "hypersensitivity pneumonitis",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "wear a respirator when working",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "oral steroids",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "X-ray of the chest shows some round glass opacities",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "CT of the lungs will also be ordered today to confirm the diagnosis",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Pulmonary function test was also ordered to assess the severity of his respiratory impairment",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_22_D2N022_terms.json
{
  "diagnoses" : [ {
    "term_text" : "Right index finger hyperextension injury",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Stenosing tenosynovitis of right index finger",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "Right index trigger finger cortisone injection",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "Corticosteroid injections",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Ibuprofen",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "MRI of the right index finger performed on 04/24/2021",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_58_D2N058_terms.json
{
  "diagnoses" : [ {
    "term_text" : "anterior STEMI",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "CAD",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "coronary artery disease",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Newly reduced left ventricular dysfunction",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "moderate mitral regurgitation",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Hypertension",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "320128"
  } ],
  "procedures" : [ {
    "term_text" : "RCA stent placement in 2018",
    "omop_domain" : "procedure_occurrence"
  }, {
    "term_text" : "drug-eluting stent placement in the LAD",
    "omop_domain" : "procedure_occurrence"
  }, {
    "term_text" : "cardiac cath lab",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "aspirin 81 mg daily",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Brilinta 90 mg twice a day",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Lipitor 80 mg daily",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Toprol 50 mg daily",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "lisinopril 20 mg a day",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Aldactone 12.5 mg daily",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "Electrocardiogram",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_66_D2N066_terms.json
{
  "diagnoses" : [ {
    "term_text" : "diabetes",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "hypertension",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "320128"
  }, {
    "term_text" : "lower back pain",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "1+ nonpitting edema of lower extremities",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "physical therapy",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "metformin 500 mg twice daily",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Norvasc",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Naprosyn 500 mg twice a day",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Flexeril 10 mg twice a day",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "Hemoglobin A1c is 7.1",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "x-ray (not ordered at this stage)",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "CBC",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "BMP",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "repeat EKG",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "chest x-ray",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ {
    "term_text" : "high cholesterol"
  }, {
    "term_text" : "ankle swelling"
  }, {
    "term_text" : "tingling in left leg"
  }, {
    "term_text" : "negative Homan's sign"
  } ]
}

=== Evinett/medical-term-pipeline/output/note_5_D2N005_terms.json
{
  "diagnoses" : [ {
    "term_text" : "Atrial Fibrillation",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Right middle finger distal phalanx fracture",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ ],
  "medications_and_treatments" : [ {
    "term_text" : "Digoxin",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Tramadol 50 mg every 6 hours as needed for pain",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "X-rays of the right middle finger, 3 views obtained on today's visit",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_48_D2N048_terms.json
{
  "diagnoses" : [ {
    "term_text" : "Lisfranc fracture",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Right foot pain",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "Right foot ORIF and all indicated procedures",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "Ibuprofen",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "3 views of the right foot were taken",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ {
    "term_text" : "Subtle dorsal displacement of the base of the 2nd metatarsal with a 3 mm separation of the 1st and 2nd metatarsal bases"
  }, {
    "term_text" : "Presence of a bony fragment in the Lisfranc joint space"
  } ]
}

=== Evinett/medical-term-pipeline/output/note_28_D2N028_terms.json
{
  "diagnoses" : [ {
    "term_text" : "abdominal pain",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "chronic abdominal pain",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "constipation",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "Start daily fiber supplement",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Increase water consumption to at least 48 ounces daily",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Avoid trigger foods that may cause episodes of diarrhea",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Repeat liver enzyme labs today",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Schedule a liver ultrasound pending lab results",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Encouraged to cease alcohol consumption",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Patient to contact his PCP to discuss alternative medications",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "Crestor",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "olmesartan daily",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Tylenol as needed for pain",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "CT scan of abdomen (01/23/2020)",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ {
    "term_text" : "constipation"
  }, {
    "term_text" : "diarrhea"
  }, {
    "term_text" : "mild left periumbilical tenderness to palpation"
  }, {
    "term_text" : "mild hepatomegaly"
  }, {
    "term_text" : "increased stool burden in colon"
  }, {
    "term_text" : "elevated liver enzymes (AST and ALT)"
  } ]
}
