=== Evinett/medical-term-pipeline/src/main/resources/output_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Extracted Medical Terms",
  "type": "object",
  "properties": {
    "diagnoses": {
      "$ref": "#/definitions/structuredTermArray"
    },
    "procedures": {
      "$ref": "#/definitions/structuredTermArray"
    },
    "medications_and_treatments": {
      "$ref": "#/definitions/medicationTermArray"
    },
    "tests": {
      "$ref": "#/definitions/structuredTermArray"
    },
    "clinical_narrative": {
      "$ref": "#/definitions/narrativeTermArray"
    }
  },
  "required": [
    "diagnoses",
    "procedures",
    "medications_and_treatments",
    "tests",
    "clinical_narrative"
  ],
  "definitions": {
    "structuredTermObject": {
      "type": "object",
      "properties": {
        "term_text": {
          "type": "string",
          "minLength": 1
        },
        "omop_domain": {
          "type": "string",
          "minLength": 1
        },
        "OMOP_ID": {
          "type": "string"
        }
      },
      "required": [
        "term_text",
        "omop_domain"
      ],
      "additionalProperties": false
    },
    "medicationTermObject": {
      "type": "object",
      "properties": {
        "term_text": {
          "type": "string",
          "minLength": 1
        },
        "omop_domain": {
          "type": "string",
          "minLength": 1
        },
        "OMOP_ID": {
          "type": "string"
        },
        "details": {
          "type": "object"
        }
      },
      "required": [
        "term_text",
        "omop_domain"
      ],
      "additionalProperties": false
    },
    "narrativeTermObject": {
      "type": "object",
      "properties": {
        "term_text": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "term_text"
      ],
      "additionalProperties": false
    },
    "structuredTermArray": {
      "type": "array",
      "items": { "$ref": "#/definitions/structuredTermObject" }
    },
    "medicationTermArray": {
      "type": "array",
      "items": { "$ref": "#/definitions/medicationTermObject" }
    },
    "narrativeTermArray": {
      "type": "array",
      "items": { "$ref": "#/definitions/narrativeTermObject" }
    }
  }
}

=== Evinett/medical-term-pipeline/output/note_29_D2N029_terms.json
{
  "diagnoses" : [ {
    "term_text" : "Melanoma",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Stage 1 melanoma",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Augmentin",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "Wide local excision with a 1-2 cm margin",
    "omop_domain" : "procedure_occurrence"
  }, {
    "term_text" : "Primary closure or skin graft closure",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ ],
  "tests" : [ {
    "term_text" : "Pathology Report",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Histology",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Clark level",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Breslow thickness",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Radial growth phase",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Vertical growth phase",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Mitotic figures",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Ulceration",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Regression",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Lymphatic invasion",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Perineural invasion",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Microscopic satellitosis",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Infiltrating lymphocytes",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Melanocytic nevus",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Predominant cytology",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Peripheral margin",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Deep margin",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_4_D2N004_terms.json
{
  "diagnoses" : [ {
    "term_text" : "congestive heart failure",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "319835"
  }, {
    "term_text" : "type 2 diabetes",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "back pain",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "4046660"
  }, {
    "term_text" : "Grade 2/6 systolic ejection murmur",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Acute lumbar strain",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Diabetes type 2",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "golfing",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Refer to physical therapy",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Increase metformin to 1000 mg twice daily",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "Tylenol",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "ibuprofen",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "meloxicam 15 mg once daily",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "lisinopril 20 mg once daily",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Lasix",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "X-ray lumbar spine is unremarkable",
    "omop_domain" : "observation",
    "OMOP_ID" : "40482354"
  }, {
    "term_text" : "Hemoglobin A1c is elevated at 8",
    "omop_domain" : "measurement",
    "OMOP_ID" : "40762352"
  }, {
    "term_text" : "Repeat hemoglobin A1c in a couple of months",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_53_D2N053_terms.json
{
  "diagnoses" : [ {
    "term_text" : "Scalp psoriasis",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "Examination: Scalp reveals demarcated scaly, erythematous plaques.",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "clobetasol 0.05%",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "T/Gel shampoo",
    "omop_domain" : "device_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "BP: 130/68",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "HR: 98",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "RR:18",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Temperature is 97.7 today",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_44_D2N044_terms.json
{
  "diagnoses" : [ {
    "term_text" : "Bilateral knee pain",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Patellofemoral pain syndrome, bilateral",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "Refer to physical therapy",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "over-the-counter NSAIDs",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "X-ray of the bilateral knees are reviewed",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "MRI (previous)",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_12_D2N012_terms.json
{
  "diagnoses" : [ {
    "term_text" : "depression",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "4149320"
  }, {
    "term_text" : "Asthma",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "317009"
  }, {
    "term_text" : "Diabetes Type II",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "Continue on albuterol, 2 puffs every 4-6 hours as needed",
    "omop_domain" : "procedure_occurrence"
  }, {
    "term_text" : "Start on Zoloft 25 mg once a day",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "Prozac 20 mg daily",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Symbicort 2 puffs twice a day during the summer",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "metformin (increased to 1000 mg twice a day)",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "PFT (within normal limits)",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Diabetes panel (glucose and hemoglobin A1c elevated)",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "X-ray of the chest is unremarkable",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Repeat hemoglobin A1c in 3 months",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Continue to monitor blood glucose levels at home",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_47_D2N047_terms.json
{
  "diagnoses" : [ {
    "term_text" : "coronary artery disease",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "diabetes",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "refer to a urologist",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "Flomax 0.4 mg once at night",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Lipitor 40 mg a day",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "aspirin",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "metoprolol",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "metformin 1000 mg twice a day",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "PSA",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "urinalysis",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "urine culture",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "echocardiogram",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "lipid panel",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_46_D2N046_terms.json
{
  "diagnoses" : [ {
    "term_text" : "ovarian cancer",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "abdominal pain",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "stage IIIA disease",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "surgical intervention",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "hysterectomy",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "oophorectomy",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "lymph node dissection",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "genetic counseling and testing",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "cisplatin and Taxol",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "CT scan of the abdomen",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "CA-125",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "hCG",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "AFP",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "LDH",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ {
    "term_text" : "unintentional weight loss"
  }, {
    "term_text" : "constipation"
  }, {
    "term_text" : "abnormal vaginal bleeding"
  }, {
    "term_text" : "depression"
  }, {
    "term_text" : "left lower quadrant tenderness to palpation"
  }, {
    "term_text" : "left adnexal mass"
  }, {
    "term_text" : "3 cm left ovarian mass with associated localized lymph node involvement"
  } ]
}

=== Evinett/medical-term-pipeline/output/note_43_D2N043_terms.json
{
  "diagnoses" : [ {
    "term_text" : "type 2 diabetes",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "gout",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "2/6 Systolic ejection murmur",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Nicotine dependence",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "nicotine patch",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "allopurinol",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "21 mg nicotine patch",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "Hemoglobin A1c",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ {
    "term_text" : "smoking cessation"
  }, {
    "term_text" : "impending fatherhood"
  } ]
}
