=== Evinett/medical-term-pipeline/src/main/resources/output_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Extracted Medical Terms",
  "type": "object",
  "properties": {
    "diagnoses": {
      "$ref": "#/definitions/structuredTermArray"
    },
    "procedures": {
      "$ref": "#/definitions/structuredTermArray"
    },
    "medications_and_treatments": {
      "$ref": "#/definitions/medicationTermArray"
    },
    "tests": {
      "$ref": "#/definitions/structuredTermArray"
    },
    "clinical_narrative": {
      "$ref": "#/definitions/narrativeTermArray"
    }
  },
  "required": [
    "diagnoses",
    "procedures",
    "medications_and_treatments",
    "tests",
    "clinical_narrative"
  ],
  "definitions": {
    "structuredTermObject": {
      "type": "object",
      "properties": {
        "term_text": {
          "type": "string",
          "minLength": 1
        },
        "omop_domain": {
          "type": "string",
          "minLength": 1
        },
        "OMOP_ID": {
          "type": "string"
        }
      },
      "required": [
        "term_text",
        "omop_domain"
      ],
      "additionalProperties": false
    },
    "medicationTermObject": {
      "type": "object",
      "properties": {
        "term_text": {
          "type": "string",
          "minLength": 1
        },
        "omop_domain": {
          "type": "string",
          "minLength": 1
        },
        "OMOP_ID": {
          "type": "string"
        },
        "details": {
          "type": "object"
        }
      },
      "required": [
        "term_text",
        "omop_domain"
      ],
      "additionalProperties": false
    },
    "narrativeTermObject": {
      "type": "object",
      "properties": {
        "term_text": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "term_text"
      ],
      "additionalProperties": false
    },
    "structuredTermArray": {
      "type": "array",
      "items": { "$ref": "#/definitions/structuredTermObject" }
    },
    "medicationTermArray": {
      "type": "array",
      "items": { "$ref": "#/definitions/medicationTermObject" }
    },
    "narrativeTermArray": {
      "type": "array",
      "items": { "$ref": "#/definitions/narrativeTermObject" }
    }
  }
}

=== Evinett/medical-term-pipeline/output/note_45_D2N045_terms.json
{
  "diagnoses" : [ {
    "term_text" : "Right knee sprain",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "Refer to physical therapy",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "Tylenol 500 mg, 2 tablets",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "ibuprofen 200 mg, 2 tablets",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "X-rays of the right knee were obtained and reviewed in office today",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_20_D2N020_terms.json
{
  "diagnoses" : [ {
    "term_text" : "anemia",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "439777"
  }, {
    "term_text" : "gastritis",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "Endoscopy from the emergency room",
    "omop_domain" : "procedure_occurrence"
  }, {
    "term_text" : "polypectomy",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "Protonix 40 mg once a day",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "Hemoglobin- 8.2",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "biopsy results are still pending",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Repeat CBC was ordered",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_30_D2N030_terms.json
{
  "diagnoses" : [ {
    "term_text" : "bilateral breast cysts",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "anxiety",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "breast cancer (family history)",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "Covid vaccinations",
    "omop_domain" : "procedure_occurrence"
  }, {
    "term_text" : "follow-up bilateral breast cysts",
    "omop_domain" : "procedure_occurrence"
  }, {
    "term_text" : "continue close monitoring and refer to breast specialist",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "progesterone",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "vaginal cream",
    "omop_domain" : "device_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Buspar",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Singulair",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Camila birth control",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "pap smear is negative/negative (2019)",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "pap smear is abnormal (2009)",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "physical exam, genitourinary, breast density",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_2_D2N002_terms.json
{
  "diagnoses" : [ {
    "term_text" : "joint pain",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "arthritis",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "hypothyroidism",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "polycystic kidneys",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "kidney transplant",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "Tylenol",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Synthroid",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Ultram 50 mg every 6 hours as needed",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "X-ray of the right knee is unremarkable",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Labs: Within normal limits. White blood cell count is within normal limits. Kidney function is normal",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Autoimmune panel",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Thyroid panel",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_41_D2N041_terms.json
{
  "diagnoses" : [ {
    "term_text" : "hypertension",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "320128"
  }, {
    "term_text" : "diabetes",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Sore throat",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "rapid strep test",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "amoxicillin 500 mg 3 times a day for 10 days",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "lidocaine swish and swallow",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "ibuprofen",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "lisinopril 40 mg once a day",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "Rapid COVID-19 test is negative",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Lipid panel ordered",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Hemoglobin A1c",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_36_D2N036_terms.json
{
  "diagnoses" : [ {
    "term_text" : "bilateral carpal tunnel syndrome",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "wear a wrist splint",
    "omop_domain" : "procedure_occurrence"
  }, {
    "term_text" : "limit active repetitive motions while working for the next 2 weeks",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "ibuprofen 600 mg every 6 hours",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "EMG of the bilateral upper extremities",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}

=== Evinett/medical-term-pipeline/output/note_63_D2N063_terms.json
{
  "diagnoses" : [ {
    "term_text" : "dyspnea",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "diabetes",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "congestive heart failure",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "319835"
  }, {
    "term_text" : "chronic obstructive pulmonary disease",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "exacerbation of congestive heart failure",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "diabetes type 2",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "increase dose of Lasix from 20 mg to 60 mg for the next 4 days",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "physical therapy",
    "omop_domain" : "procedure_occurrence",
    "OMOP_ID" : "0"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "Lasix",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "albuterol",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Atrovent",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "metformin",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Naprosyn",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Flexeril",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "Hemoglobin A1c is 7.5",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "repeat hemoglobin A1c",
    "omop_domain" : "measurement",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ {
    "term_text" : "10 pound weight gain"
  }, {
    "term_text" : "elevated blood glucose levels"
  } ]
}

=== Evinett/medical-term-pipeline/output/note_17_D2N017_terms.json
{
  "diagnoses" : [ {
    "term_text" : "atopic eczema",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Right leg contusion",
    "omop_domain" : "condition_occurrence",
    "OMOP_ID" : "0"
  } ],
  "procedures" : [ {
    "term_text" : "colectomy",
    "omop_domain" : "procedure_occurrence"
  } ],
  "medications_and_treatments" : [ {
    "term_text" : "Fluocinonide topical cream",
    "omop_domain" : "device_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Tylenol",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "ibuprofen",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  }, {
    "term_text" : "Mobic 15 mg once a day",
    "omop_domain" : "drug_exposure",
    "OMOP_ID" : "0"
  } ],
  "tests" : [ {
    "term_text" : "X-rays of the right lower extremity is normal, no fractures or dislocations",
    "omop_domain" : "observation",
    "OMOP_ID" : "0"
  } ],
  "clinical_narrative" : [ ]
}
